spring.config.import=optional:file:.env[.properties]
server.port=${PORT:4000}
spring.data.mongodb.uri=${MONGODB_URI:mongodb://127.0.0.1:27017}
spring.data.mongodb.database=${MONGODB_DB_NAME:dealnest}
